#!/bin/sh
set -e

case "$1" in
    configure)
        update-mime-database /usr/share/mime || true
        update-desktop-database /usr/share/applications || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
